---
# tasks file for network
- name: Set a Static IP for OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    ifname: "{{ service_node_internal_interface }}"
    type: ethernet
    ip4: "{{ service_node_internal_ip }}"
    dns4: "{{ service_node_internal_dns_server }}"
    gw4: ""
    state: present

- name: Set search domain for OCP network interface
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ service_node_internal_interface }}
    regexp: '^DOMAIN='
    line: 'DOMAIN="{{ service_node_internal_search_domain }}"'
    state: present

- name: Set never use this network for default route for OCP network interface
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ service_node_internal_interface }}
    regexp: '^DEFROUTE='
    line: "DEFROUTE=\"{{ service_node_internal_default_route | ternary('yes', 'no') }}\""
    state: present

- name: Set automatically connect for OCP network interface
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-{{ service_node_internal_interface }}
    regexp: '^ONBOOT='
    line: "ONBOOT=\"{{ service_node_internal_auto_connect | ternary('yes', 'no') }}\""
    state: present

- name: Restart OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    state: restarted

#this is a test
