---
# tasks file for network
- name: Set a Static IP for OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    ifname: "{{ service_node_internal_interface }}"
    type: ethernet
    ip4: "{{ service_node_internal_ip }}"
    dns4: "{{ service_node_internal_dns_server }}"
    gw4: "{{ service_node_external_ip }}"
    state: present

- name: Set search domain for OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    type: ethernet
    dns4_search: "{{ service_node_internal_search_domain }}"
    state: present

- name: Set never use this network for default route for OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    type: ethernet
    never_default4: "{{ not service_node_internal_default_route | bool }}"
    state: present

- name: Set automatically connect for OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    type: ethernet
    autoconnect: "{{ service_node_internal_auto_connect | bool }}"
    state: present

- name: Restart OCP network interface
  community.general.nmcli:
    conn_name: "{{ service_node_internal_interface }}"
    state: present