# tasks file for nfs
- name: Install NFS Server
  ansible.builtin.dnf:
    name: nfs-utils
    state: latest

- name: Create the Share
  ansible.builtin.file:
    path: "{{ nfs_registry_share_dir }}"
    state: directory
    owner: "{{ nfs_registry_share_owner }}"
    group: "{{ nfs_registry_share_group }}"
    mode: "{{ nfs_registry_share_mode }}"

- name: Add the Share to /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ nfs_registry_share_dir }} {{ nfs_registry_export_network }}({{ nfs_registry_export_options }})"
    state: present

- name: Export the Share
  ansible.builtin.shell: exportfs -ra

- name: Set Firewall rules
  ansible.posix.firewalld:
    zone: "{{ nfs_registry_firewall_zone }}"
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - mountd
    - rpc-bind
    - nfs

- name: Enable and start the NFS related services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - nfs-server
    - rpcbind
    - nfs-mountd

- name: Mount the NFS export on a remote host
  ansible.posix.mount:
    path: /mnt # The mount point on the remote host
    src: "{{ service_node_internal_ip }}:/var/nfs/registry" # The NFS export source
    fstype: nfs # The file system type
    state: mounted # The desired state of the mount point

